functionsDirectory = "/Users/lucamorigi/progetti/NeuroScacchi/netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/lucamorigi/progetti/NeuroScacchi/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install && npm run build"
functions = "/Users/lucamorigi/progetti/NeuroScacchi/netlify/functions"

[build.environment]
SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]