// Stili condivisi per tutte le sezioni della pagina Metodo

export const styles = {
  container: {
    maxWidth: 640,
    margin: '0 auto',
    padding: '24px 20px 80px',
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
  },
  topBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  backBtn: {
    background: 'none',
    border: 'none',
    fontSize: 14,
    color: '#5A6C7D',
    cursor: 'pointer',
    padding: '4px 0',
    fontFamily: 'inherit',
  },
  pdfBtn: {
    padding: '8px 16px',
    background: '#2C3E50',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  title: {
    fontSize: 24,
    fontWeight: 700,
    color: '#2C3E50',
    margin: 0,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 15,
    color: '#5A6C7D',
    margin: 0,
    textAlign: 'center',
    lineHeight: 1.5,
  },
  legend: {
    display: 'flex',
    justifyContent: 'center',
    gap: 20,
    flexWrap: 'wrap',
    padding: '8px 0',
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 12,
    color: '#5A6C7D',
  },
  dot: {
    display: 'inline-block',
    width: 10,
    height: 10,
    borderRadius: '50%',
  },
  partTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: '#78909C',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    margin: '24px 0 4px',
    paddingBottom: 8,
    borderBottom: '2px solid #CFD8DC',
  },
  roadmapContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    padding: '8px 0',
  },
  section: {
    borderRadius: 10,
    padding: '16px 20px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  statusBadge: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 700,
    padding: '2px 8px',
    borderRadius: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    whiteSpace: 'nowrap',
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: 600,
    color: '#2C3E50',
    margin: 0,
  },
  sectionBody: {
    fontSize: 14,
    color: '#37474F',
    lineHeight: 1.7,
  },
  list: {
    margin: '8px 0',
    paddingLeft: 20,
    lineHeight: 1.8,
  },
  note: {
    fontSize: 13,
    color: '#78909C',
    fontStyle: 'italic',
    marginTop: 8,
  },
  implBox: {
    background: '#E8F5E9',
    border: '1px solid #C8E6C9',
    borderRadius: 8,
    padding: '10px 14px',
    fontSize: 13,
    color: '#2E7D32',
    lineHeight: 1.6,
    margin: '10px 0',
  },
  evolutionBox: {
    background: '#FFF8E1',
    border: '1px solid #FFE082',
    borderRadius: 8,
    padding: '10px 14px',
    fontSize: 13,
    color: '#E65100',
    lineHeight: 1.6,
    margin: '10px 0',
  },
  warningBox: {
    background: '#FFF3E0',
    border: '1px solid #FFE0B2',
    borderRadius: 8,
    padding: '12px 16px',
    fontSize: 13,
    color: '#E65100',
    lineHeight: 1.6,
    margin: '10px 0',
  },
  infoBox: {
    background: '#E3F2FD',
    border: '1px solid #90CAF9',
    borderRadius: 8,
    padding: '10px 14px',
    fontSize: 13,
    color: '#1565C0',
    lineHeight: 1.6,
    margin: '10px 0',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    marginTop: 12,
    fontSize: 13,
  },
  th: {
    textAlign: 'left',
    padding: '8px 10px',
    background: '#ECEFF1',
    borderBottom: '2px solid #CFD8DC',
    fontSize: 12,
    fontWeight: 700,
    color: '#37474F',
  },
  td: {
    padding: '6px 10px',
    borderBottom: '1px solid #E0E0E0',
    color: '#546E7A',
    lineHeight: 1.5,
  },
  paramGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: 12,
    marginTop: 12,
  },
  paramCard: {
    background: '#fff',
    border: '1px solid #C8E6C9',
    borderRadius: 8,
    padding: '12px 14px',
  },
  paramName: {
    fontSize: 14,
    fontWeight: 700,
    color: '#2C3E50',
    marginBottom: 2,
  },
  paramFoundation: {
    fontSize: 11,
    fontWeight: 600,
    color: '#78909C',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  paramDesc: {
    fontSize: 12,
    color: '#78909C',
    marginBottom: 6,
  },
  paramEffect: {
    fontSize: 12,
    fontWeight: 600,
    color: '#2E7D32',
    background: '#E8F5E9',
    padding: '3px 8px',
    borderRadius: 4,
    display: 'inline-block',
    marginBottom: 6,
  },
  paramDetail: {
    fontSize: 12,
    color: '#546E7A',
    lineHeight: 1.5,
  },
  footer: {
    textAlign: 'center',
    paddingTop: 16,
    borderTop: '1px solid #E0E0E0',
  },
  footerText: {
    fontSize: 12,
    color: '#B0BEC5',
    margin: 0,
  },
  copyright: {
    textAlign: 'center',
    padding: '16px 20px',
    marginTop: 8,
    background: '#ECEFF1',
    borderRadius: 8,
    border: '1px solid #CFD8DC',
  },
  copyrightText: {
    fontSize: 11,
    color: '#546E7A',
    margin: '0 0 4px 0',
    lineHeight: 1.5,
  },
  // Stili per colori (Design System)
  colorRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '4px 0',
    fontSize: 13,
  },
  colorSwatch: {
    width: 28,
    height: 28,
    borderRadius: 6,
    border: '1px solid rgba(0,0,0,0.1)',
    flexShrink: 0,
  },
  colorCode: {
    fontFamily: 'monospace',
    fontSize: 12,
    color: '#78909C',
    minWidth: 70,
  },
  // Firebase tree
  codeTree: {
    fontFamily: 'monospace',
    fontSize: 12,
    lineHeight: 1.8,
    color: '#37474F',
    background: '#ECEFF1',
    borderRadius: 8,
    padding: '12px 16px',
    margin: '10px 0',
    whiteSpace: 'pre',
    overflowX: 'auto',
  },
  // Checklist
  checklistItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    padding: '4px 0',
    fontSize: 13,
    color: '#37474F',
    lineHeight: 1.6,
  },
  checklistNumber: {
    flexShrink: 0,
    width: 22,
    height: 22,
    borderRadius: '50%',
    background: '#283593',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 11,
    fontWeight: 700,
  },
}
